fix

diff --git a/plan/action.yml b/plan/action.yml
--- a/plan/action.yml
+++ b/plan/action.yml
@@ -24,8 +24,10 @@ runs:
     - name: Run terraform plan
       id: plan
       shell: bash
-      # workaround for continue-on-failure: true not available in composite actions
-      run: echo ""::set-output name=stdout::$( ${{ inputs.cmd }} -no-color -detailed-exitcode )" && echo "::set-output name=exitcode::0" || echo "::set-output name=exitcode::$?"
+      run: |
+        # workaround for continue-on-failure: true not available in composite actions
+        PLAN_STDOUT=$( ${{ inputs.cmd }} -no-color -detailed-exitcode ) && echo "::set-output name=exitcode::0" || echo "::set-output name=exitcode::$?"
+        echo ""::set-output name=stdout::$PLAN_STDOUT"
       working-directory: ${{ inputs.working-directory }}
 
     - name: Add PR comment if plan has changes
