enable pipefail

diff --git a/plan/action.yml b/plan/action.yml
--- a/plan/action.yml
+++ b/plan/action.yml
@@ -23,7 +23,7 @@ runs:
   steps:
     - name: Run terraform plan
       id: plan
-      shell: bash {0} # disable fail fast
+      shell: bash -o pipefail {0} # disable fail fast
       run: |
         ${{ inputs.cmd }} -detailed-exitcode -no-color 2>&1 | tee /tmp/terraform-plan.log
         echo "::set-output name=exitcode::$?"
