focs

diff --git a/plan/action.yml b/plan/action.yml
--- a/plan/action.yml
+++ b/plan/action.yml
@@ -1,5 +1,5 @@
 name: "Run terraform plan and create PR comment"
-description: "Runs terraform plan and adds a comment to the PR if it contains changes"
+description: "Runs terraform plan and adds a comment to the PR if it contains changes. Make sure to set terraform_wrapper: false on hashicorp/setup-terraform"
 
 inputs:
   cmd:
@@ -23,7 +23,8 @@ runs:
   steps:
     - name: Run terraform plan
       id: plan
-      shell: bash -o pipefail {0} # disable fail fast
+      shell: bash -o pipefail {0} # disable fail fast, we will react on the exit code manually in the steps afterwards
+      # https://trstringer.com/github-actions-multiline-strings/
       run: |
         ${{ inputs.cmd }} -detailed-exitcode -no-color 2>&1 | tee /tmp/terraform-plan.log
         echo "::set-output name=exitcode::$?"
